### ISSUE TITLE
Type instability of BLAS rules

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#343] opened 2021-01-12 19:46 UTC
During https://github.com/JuliaDiff/ChainRules.jl/pull/342
found that our BLAS rules for `gemm` and `gemv` are type-unstable  as they return a different InplaceThunk depending on the character arguments.

https://github.com/JuliaDiff/ChainRules.jl/blob/424cff38df8a757a6e91b21bbade029ab7b36a57/src/rulesets/LinearAlgebra/blas.jl#L106-L255

They should be type stable under constant folding, but his might need opaque closures (@Keno) since the constant they should check for is in in the parent scope.

We can rewrite them to push the conditions down into the inside of the `InplaceThunk`s 
It will just be a little ugly, not that they are a thing of beuty as it is.

I don't think these are very high priority as rarely does BLAS get hit, since it hits our rules for  `*` first.

**Comment by sethaxen** [comment] 2021-01-12 20:14
Duplicate of #328

**Closed** 2021-01-12 20:18 UTC
Labels: performance
